package org.blue.helper.StringHelper.persistence;

import org.apache.ibatis.annotations.Param;
import org.blue.helper.StringHelper.persistence.entity.model.UserRelation;
import org.blue.helper.StringHelper.persistence.entity.model.UserRelationExample;

import java.util.List;

public interface UserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int countByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int deleteByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int insert(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int insertSelective(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    List<UserRelation> selectByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    UserRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserRelation record, @Param("example") UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int updateByExample(@Param("record") UserRelation record, @Param("example") UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int updateByPrimaryKeySelective(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    int updateByPrimaryKey(UserRelation record);
}