package org.blue.helper.StringHelper.persistence.entity.model;

import java.sql.Timestamp;

public class FriendApplyRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.user_id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.friend_id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private Long friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.create_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.update_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.memo
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.apply_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private Timestamp applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.exp_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private Timestamp expTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_apply_record.status
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.id
     *
     * @return the value of friend_apply_record.id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.id
     *
     * @param id the value for friend_apply_record.id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.user_id
     *
     * @return the value of friend_apply_record.user_id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.user_id
     *
     * @param userId the value for friend_apply_record.user_id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.friend_id
     *
     * @return the value of friend_apply_record.friend_id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.friend_id
     *
     * @param friendId the value for friend_apply_record.friend_id
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.create_time
     *
     * @return the value of friend_apply_record.create_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.create_time
     *
     * @param createTime the value for friend_apply_record.create_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.update_time
     *
     * @return the value of friend_apply_record.update_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.update_time
     *
     * @param updateTime the value for friend_apply_record.update_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.memo
     *
     * @return the value of friend_apply_record.memo
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.memo
     *
     * @param memo the value for friend_apply_record.memo
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.apply_time
     *
     * @return the value of friend_apply_record.apply_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public Timestamp getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.apply_time
     *
     * @param applyTime the value for friend_apply_record.apply_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setApplyTime(Timestamp applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.exp_time
     *
     * @return the value of friend_apply_record.exp_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public Timestamp getExpTime() {
        return expTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.exp_time
     *
     * @param expTime the value for friend_apply_record.exp_time
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setExpTime(Timestamp expTime) {
        this.expTime = expTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_apply_record.status
     *
     * @return the value of friend_apply_record.status
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_apply_record.status
     *
     * @param status the value for friend_apply_record.status
     *
     * @mbggenerated Fri Oct 12 16:12:22 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}