package org.blue.helper.StringHelper.persistence.entity.model;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class BillRecordMonthExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public BillRecordMonthExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYIdIsNull() {
            addCriterion("y_id is null");
            return (Criteria) this;
        }

        public Criteria andYIdIsNotNull() {
            addCriterion("y_id is not null");
            return (Criteria) this;
        }

        public Criteria andYIdEqualTo(Long value) {
            addCriterion("y_id =", value, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdNotEqualTo(Long value) {
            addCriterion("y_id <>", value, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdGreaterThan(Long value) {
            addCriterion("y_id >", value, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdGreaterThanOrEqualTo(Long value) {
            addCriterion("y_id >=", value, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdLessThan(Long value) {
            addCriterion("y_id <", value, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdLessThanOrEqualTo(Long value) {
            addCriterion("y_id <=", value, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdIn(List<Long> values) {
            addCriterion("y_id in", values, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdNotIn(List<Long> values) {
            addCriterion("y_id not in", values, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdBetween(Long value1, Long value2) {
            addCriterion("y_id between", value1, value2, "yId");
            return (Criteria) this;
        }

        public Criteria andYIdNotBetween(Long value1, Long value2) {
            addCriterion("y_id not between", value1, value2, "yId");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("creat_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("creat_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Timestamp value) {
            addCriterion("creat_time =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Timestamp value) {
            addCriterion("creat_time <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Timestamp value) {
            addCriterion("creat_time >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("creat_time >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Timestamp value) {
            addCriterion("creat_time <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("creat_time <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Timestamp> values) {
            addCriterion("creat_time in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Timestamp> values) {
            addCriterion("creat_time not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("creat_time between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("creat_time not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Timestamp value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Timestamp value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Timestamp value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Timestamp value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Timestamp> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Timestamp> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("month is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("month is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(String value) {
            addCriterion("month =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(String value) {
            addCriterion("month <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(String value) {
            addCriterion("month >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(String value) {
            addCriterion("month >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(String value) {
            addCriterion("month <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(String value) {
            addCriterion("month <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLike(String value) {
            addCriterion("month like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotLike(String value) {
            addCriterion("month not like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<String> values) {
            addCriterion("month in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<String> values) {
            addCriterion("month not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(String value1, String value2) {
            addCriterion("month between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(String value1, String value2) {
            addCriterion("month not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthCountIsNull() {
            addCriterion("month_count is null");
            return (Criteria) this;
        }

        public Criteria andMonthCountIsNotNull() {
            addCriterion("month_count is not null");
            return (Criteria) this;
        }

        public Criteria andMonthCountEqualTo(Long value) {
            addCriterion("month_count =", value, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountNotEqualTo(Long value) {
            addCriterion("month_count <>", value, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountGreaterThan(Long value) {
            addCriterion("month_count >", value, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountGreaterThanOrEqualTo(Long value) {
            addCriterion("month_count >=", value, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountLessThan(Long value) {
            addCriterion("month_count <", value, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountLessThanOrEqualTo(Long value) {
            addCriterion("month_count <=", value, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountIn(List<Long> values) {
            addCriterion("month_count in", values, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountNotIn(List<Long> values) {
            addCriterion("month_count not in", values, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountBetween(Long value1, Long value2) {
            addCriterion("month_count between", value1, value2, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthCountNotBetween(Long value1, Long value2) {
            addCriterion("month_count not between", value1, value2, "monthCount");
            return (Criteria) this;
        }

        public Criteria andMonthExpIsNull() {
            addCriterion("month_exp is null");
            return (Criteria) this;
        }

        public Criteria andMonthExpIsNotNull() {
            addCriterion("month_exp is not null");
            return (Criteria) this;
        }

        public Criteria andMonthExpEqualTo(Double value) {
            addCriterion("month_exp =", value, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpNotEqualTo(Double value) {
            addCriterion("month_exp <>", value, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpGreaterThan(Double value) {
            addCriterion("month_exp >", value, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpGreaterThanOrEqualTo(Double value) {
            addCriterion("month_exp >=", value, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpLessThan(Double value) {
            addCriterion("month_exp <", value, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpLessThanOrEqualTo(Double value) {
            addCriterion("month_exp <=", value, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpIn(List<Double> values) {
            addCriterion("month_exp in", values, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpNotIn(List<Double> values) {
            addCriterion("month_exp not in", values, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpBetween(Double value1, Double value2) {
            addCriterion("month_exp between", value1, value2, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthExpNotBetween(Double value1, Double value2) {
            addCriterion("month_exp not between", value1, value2, "monthExp");
            return (Criteria) this;
        }

        public Criteria andMonthIncIsNull() {
            addCriterion("month_inc is null");
            return (Criteria) this;
        }

        public Criteria andMonthIncIsNotNull() {
            addCriterion("month_inc is not null");
            return (Criteria) this;
        }

        public Criteria andMonthIncEqualTo(Double value) {
            addCriterion("month_inc =", value, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncNotEqualTo(Double value) {
            addCriterion("month_inc <>", value, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncGreaterThan(Double value) {
            addCriterion("month_inc >", value, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncGreaterThanOrEqualTo(Double value) {
            addCriterion("month_inc >=", value, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncLessThan(Double value) {
            addCriterion("month_inc <", value, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncLessThanOrEqualTo(Double value) {
            addCriterion("month_inc <=", value, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncIn(List<Double> values) {
            addCriterion("month_inc in", values, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncNotIn(List<Double> values) {
            addCriterion("month_inc not in", values, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncBetween(Double value1, Double value2) {
            addCriterion("month_inc between", value1, value2, "monthInc");
            return (Criteria) this;
        }

        public Criteria andMonthIncNotBetween(Double value1, Double value2) {
            addCriterion("month_inc not between", value1, value2, "monthInc");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill_record_month
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 21 17:12:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
