package org.blue.helper.StringHelper.persistence.entity.model;

import java.util.Date;

public class UserRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.user_id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.friend_id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    private Long friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.create_time
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.update_time
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.remark_name
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    private String remarkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.intimacy
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    private Integer intimacy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.status
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.id
     *
     * @return the value of user_relation.id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.id
     *
     * @param id the value for user_relation.id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.user_id
     *
     * @return the value of user_relation.user_id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.user_id
     *
     * @param userId the value for user_relation.user_id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.friend_id
     *
     * @return the value of user_relation.friend_id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.friend_id
     *
     * @param friendId the value for user_relation.friend_id
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.create_time
     *
     * @return the value of user_relation.create_time
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.create_time
     *
     * @param createTime the value for user_relation.create_time
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.update_time
     *
     * @return the value of user_relation.update_time
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.update_time
     *
     * @param updateTime the value for user_relation.update_time
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.remark_name
     *
     * @return the value of user_relation.remark_name
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public String getRemarkName() {
        return remarkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.remark_name
     *
     * @param remarkName the value for user_relation.remark_name
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public void setRemarkName(String remarkName) {
        this.remarkName = remarkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.intimacy
     *
     * @return the value of user_relation.intimacy
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public Integer getIntimacy() {
        return intimacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.intimacy
     *
     * @param intimacy the value for user_relation.intimacy
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public void setIntimacy(Integer intimacy) {
        this.intimacy = intimacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.status
     *
     * @return the value of user_relation.status
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.status
     *
     * @param status the value for user_relation.status
     *
     * @mbggenerated Fri Sep 07 17:35:16 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}