package org.blue.helper.StringHelper.persistence;

import org.apache.ibatis.annotations.Param;
import org.blue.helper.StringHelper.persistence.entity.model.LoginRecord;
import org.blue.helper.StringHelper.persistence.entity.model.LoginRecordExample;

import java.util.List;
import java.util.Map;

public interface LoginRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int countByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int deleteByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int insert(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int insertSelective(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    List<LoginRecord> selectByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    LoginRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoginRecord record, @Param("example") LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int updateByExample(@Param("record") LoginRecord record, @Param("example") LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int updateByPrimaryKeySelective(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    int updateByPrimaryKey(LoginRecord record);

    List<LoginRecord> getUserRecordByToken(Map<String,Object> map);

    int updateStatusByTokenAndIp(@Param("token") String token,@Param("loginIp") String loginIp);

    int updateRenewal(Map<String,Object> map);

}