package org.blue.helper.StringHelper.persistence.entity.model;

import java.sql.Timestamp;

public class BillType {//implements Comparable<BillType>
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_type.id
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_type.create_time
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_type.modify_time
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    private Timestamp modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_type.type_code
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_type.p_code
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_type.type_name
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_type.type_img
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    private String typeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_type.status
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_type.id
     *
     * @return the value of bill_type.id
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_type.id
     *
     * @param id the value for bill_type.id
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_type.create_time
     *
     * @return the value of bill_type.create_time
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_type.create_time
     *
     * @param createTime the value for bill_type.create_time
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_type.modify_time
     *
     * @return the value of bill_type.modify_time
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public Timestamp getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_type.modify_time
     *
     * @param modifyTime the value for bill_type.modify_time
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_type.type_code
     *
     * @return the value of bill_type.type_code
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_type.type_code
     *
     * @param typeCode the value for bill_type.type_code
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_type.p_code
     *
     * @return the value of bill_type.p_code
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_type.p_code
     *
     * @param pCode the value for bill_type.p_code
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public void setpCode(String pCode) {
        this.pCode = pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_type.type_name
     *
     * @return the value of bill_type.type_name
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_type.type_name
     *
     * @param typeName the value for bill_type.type_name
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_type.type_img
     *
     * @return the value of bill_type.type_img
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public String getTypeImg() {
        return typeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_type.type_img
     *
     * @param typeImg the value for bill_type.type_img
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public void setTypeImg(String typeImg) {
        this.typeImg = typeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_type.status
     *
     * @return the value of bill_type.status
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_type.status
     *
     * @param status the value for bill_type.status
     *
     * @mbggenerated Tue Nov 27 10:11:58 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

//    @Override
//    public int compareTo(BillType billType) {
//        long i = this.getId() - billType.getId();//先按照年龄排序
//        if (i<0L){
//            return 1;
//        }else if (i==0L){
//            return 0;
//        }else{
//            return -1;
//        }
//    }

}
