package org.blue.helper.StringHelper.persistence.entity.model;

import java.sql.Timestamp;

public class CloudStorage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.p_id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private Long pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.user_id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.file_name
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.file_type
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.file_size
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private Double fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.created_time
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private Timestamp createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.update_time
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_storage.status
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.id
     *
     * @return the value of cloud_storage.id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.id
     *
     * @param id the value for cloud_storage.id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.p_id
     *
     * @return the value of cloud_storage.p_id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.p_id
     *
     * @param pId the value for cloud_storage.p_id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setpId(Long pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.user_id
     *
     * @return the value of cloud_storage.user_id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.user_id
     *
     * @param userId the value for cloud_storage.user_id
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.file_name
     *
     * @return the value of cloud_storage.file_name
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.file_name
     *
     * @param fileName the value for cloud_storage.file_name
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.file_type
     *
     * @return the value of cloud_storage.file_type
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.file_type
     *
     * @param fileType the value for cloud_storage.file_type
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.file_size
     *
     * @return the value of cloud_storage.file_size
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public Double getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.file_size
     *
     * @param fileSize the value for cloud_storage.file_size
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.created_time
     *
     * @return the value of cloud_storage.created_time
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public Timestamp getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.created_time
     *
     * @param createdTime the value for cloud_storage.created_time
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.update_time
     *
     * @return the value of cloud_storage.update_time
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.update_time
     *
     * @param updateTime the value for cloud_storage.update_time
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_storage.status
     *
     * @return the value of cloud_storage.status
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_storage.status
     *
     * @param status the value for cloud_storage.status
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}
