package org.blue.helper.StringHelper.persistence;

import org.apache.ibatis.annotations.Param;
import org.blue.helper.StringHelper.persistence.entity.model.BillRecord;
import org.blue.helper.StringHelper.persistence.entity.model.BillRecordExample;

import java.util.List;

public interface BillRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int countByExample(BillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int deleteByExample(BillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int insert(BillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int insertSelective(BillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    List<BillRecord> selectByExample(BillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    BillRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") BillRecord record, @Param("example") BillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int updateByExample(@Param("record") BillRecord record, @Param("example") BillRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int updateByPrimaryKeySelective(BillRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    int updateByPrimaryKey(BillRecord record);

    int updateByRecordCode(BillRecord record);
}