package org.blue.helper.StringHelper.persistence.entity.model;

import java.sql.Timestamp;

public class BillRecordYear {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.id
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.user_id
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.creat_time
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private Timestamp creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.update_time
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.year_count
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private Long yearCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.year_exp
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private Double yearExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.year_inc
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private Double yearInc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_year.status
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.id
     *
     * @return the value of bill_record_year.id
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.id
     *
     * @param id the value for bill_record_year.id
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.user_id
     *
     * @return the value of bill_record_year.user_id
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.user_id
     *
     * @param userId the value for bill_record_year.user_id
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.creat_time
     *
     * @return the value of bill_record_year.creat_time
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public Timestamp getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.creat_time
     *
     * @param creatTime the value for bill_record_year.creat_time
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setCreatTime(Timestamp creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.update_time
     *
     * @return the value of bill_record_year.update_time
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.update_time
     *
     * @param updateTime the value for bill_record_year.update_time
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.year
     *
     * @return the value of bill_record_year.year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.year
     *
     * @param year the value for bill_record_year.year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.year_count
     *
     * @return the value of bill_record_year.year_count
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public Long getYearCount() {
        return yearCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.year_count
     *
     * @param yearCount the value for bill_record_year.year_count
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setYearCount(Long yearCount) {
        this.yearCount = yearCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.year_exp
     *
     * @return the value of bill_record_year.year_exp
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public Double getYearExp() {
        return yearExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.year_exp
     *
     * @param yearExp the value for bill_record_year.year_exp
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setYearExp(Double yearExp) {
        this.yearExp = yearExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.year_inc
     *
     * @return the value of bill_record_year.year_inc
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public Double getYearInc() {
        return yearInc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.year_inc
     *
     * @param yearInc the value for bill_record_year.year_inc
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setYearInc(Double yearInc) {
        this.yearInc = yearInc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_year.status
     *
     * @return the value of bill_record_year.status
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_year.status
     *
     * @param status the value for bill_record_year.status
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}
