package org.blue.helper.StringHelper.persistence.entity.model;

import java.sql.Timestamp;

public class BillRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.id
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.d_id
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private Long dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.record_code
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private String recordCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.creat_time
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private Timestamp creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.update_time
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.bill_type
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private String billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.bill_money
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private Double billMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.bill_depict
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private String billDepict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record.status
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.id
     *
     * @return the value of bill_record.id
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.id
     *
     * @param id the value for bill_record.id
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.d_id
     *
     * @return the value of bill_record.d_id
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.d_id
     *
     * @param dId the value for bill_record.d_id
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.record_code
     *
     * @return the value of bill_record.record_code
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public String getRecordCode() {
        return recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.record_code
     *
     * @param recordCode the value for bill_record.record_code
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setRecordCode(String recordCode) {
        this.recordCode = recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.creat_time
     *
     * @return the value of bill_record.creat_time
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public Timestamp getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.creat_time
     *
     * @param creatTime the value for bill_record.creat_time
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setCreatTime(Timestamp creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.update_time
     *
     * @return the value of bill_record.update_time
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.update_time
     *
     * @param updateTime the value for bill_record.update_time
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.bill_type
     *
     * @return the value of bill_record.bill_type
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.bill_type
     *
     * @param billType the value for bill_record.bill_type
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setBillType(String billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.bill_money
     *
     * @return the value of bill_record.bill_money
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public Double getBillMoney() {
        return billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.bill_money
     *
     * @param billMoney the value for bill_record.bill_money
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setBillMoney(Double billMoney) {
        this.billMoney = billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.bill_depict
     *
     * @return the value of bill_record.bill_depict
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public String getBillDepict() {
        return billDepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.bill_depict
     *
     * @param billDepict the value for bill_record.bill_depict
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setBillDepict(String billDepict) {
        this.billDepict = billDepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record.status
     *
     * @return the value of bill_record.status
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record.status
     *
     * @param status the value for bill_record.status
     *
     * @mbggenerated Wed Nov 21 14:48:23 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}