package org.blue.helper.StringHelper.persistence.entity.model;

import java.sql.Timestamp;

public class BillRecordMonth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.id
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.y_id
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private Long yId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.creat_time
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private Timestamp creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.update_time
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.month_count
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private Long monthCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.month_exp
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private Double monthExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.month_inc
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private Double monthInc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_month.status
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.id
     *
     * @return the value of bill_record_month.id
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.id
     *
     * @param id the value for bill_record_month.id
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.y_id
     *
     * @return the value of bill_record_month.y_id
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Long getyId() {
        return yId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.y_id
     *
     * @param yId the value for bill_record_month.y_id
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setyId(Long yId) {
        this.yId = yId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.creat_time
     *
     * @return the value of bill_record_month.creat_time
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Timestamp getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.creat_time
     *
     * @param creatTime the value for bill_record_month.creat_time
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setCreatTime(Timestamp creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.update_time
     *
     * @return the value of bill_record_month.update_time
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.update_time
     *
     * @param updateTime the value for bill_record_month.update_time
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.month
     *
     * @return the value of bill_record_month.month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.month
     *
     * @param month the value for bill_record_month.month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.month_count
     *
     * @return the value of bill_record_month.month_count
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Long getMonthCount() {
        return monthCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.month_count
     *
     * @param monthCount the value for bill_record_month.month_count
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setMonthCount(Long monthCount) {
        this.monthCount = monthCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.month_exp
     *
     * @return the value of bill_record_month.month_exp
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Double getMonthExp() {
        return monthExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.month_exp
     *
     * @param monthExp the value for bill_record_month.month_exp
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setMonthExp(Double monthExp) {
        this.monthExp = monthExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.month_inc
     *
     * @return the value of bill_record_month.month_inc
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Double getMonthInc() {
        return monthInc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.month_inc
     *
     * @param monthInc the value for bill_record_month.month_inc
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setMonthInc(Double monthInc) {
        this.monthInc = monthInc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_month.status
     *
     * @return the value of bill_record_month.status
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_month.status
     *
     * @param status the value for bill_record_month.status
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}
