package org.blue.helper.StringHelper.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.blue.helper.StringHelper.persistence.entity.model.BillRecordYear;
import org.blue.helper.StringHelper.persistence.entity.model.BillRecordYearExample;

public interface BillRecordYearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    int countByExample(BillRecordYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    int deleteByExample(BillRecordYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    int insert(BillRecordYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    Long insertSelective(BillRecordYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    List<BillRecordYear> selectByExample(BillRecordYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    BillRecordYear selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") BillRecordYear record, @Param("example") BillRecordYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    int updateByExample(@Param("record") BillRecordYear record, @Param("example") BillRecordYearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    int updateByPrimaryKeySelective(BillRecordYear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_year
     *
     * @mbggenerated Thu Nov 22 09:19:44 CST 2018
     */
    int updateByPrimaryKey(BillRecordYear record);

    BillRecordYear  getTotleAmount(@Param("year")String year,@Param("userId")Long userId);
}
