package org.blue.helper.StringHelper.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.blue.helper.StringHelper.persistence.entity.model.BillRecordMonth;
import org.blue.helper.StringHelper.persistence.entity.model.BillRecordMonthExample;

public interface BillRecordMonthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    int countByExample(BillRecordMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    int deleteByExample(BillRecordMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    int insert(BillRecordMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    Long insertSelective(BillRecordMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    List<BillRecordMonth> selectByExample(BillRecordMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    BillRecordMonth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") BillRecordMonth record, @Param("example") BillRecordMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    int updateByExample(@Param("record") BillRecordMonth record, @Param("example") BillRecordMonthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    int updateByPrimaryKeySelective(BillRecordMonth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_record_month
     *
     * @mbggenerated Wed Nov 21 17:12:44 CST 2018
     */
    int updateByPrimaryKey(BillRecordMonth record);
}
