package org.blue.helper.StringHelper.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.blue.helper.StringHelper.persistence.entity.model.CloudStorage;
import org.blue.helper.StringHelper.persistence.entity.model.CloudStorageExample;

public interface CloudStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int countByExample(CloudStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int deleteByExample(CloudStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int insert(CloudStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int insertSelective(CloudStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    List<CloudStorage> selectByExample(CloudStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    CloudStorage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") CloudStorage record, @Param("example") CloudStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int updateByExample(@Param("record") CloudStorage record, @Param("example") CloudStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int updateByPrimaryKeySelective(CloudStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_storage
     *
     * @mbggenerated Fri Dec 28 09:56:01 CST 2018
     */
    int updateByPrimaryKey(CloudStorage record);

    Long selectIdByFileNameAndFileType(CloudStorage record);
}
