package org.blue.helper.StringHelper.persistence;

import org.apache.ibatis.annotations.Param;
import org.blue.helper.StringHelper.persistence.entity.model.OfflineMsg;
import org.blue.helper.StringHelper.persistence.entity.model.OfflineMsgExample;

import java.util.List;

public interface OfflineMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int countByExample(OfflineMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int deleteByExample(OfflineMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int insert(OfflineMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int insertSelective(OfflineMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    List<OfflineMsg> selectByExample(OfflineMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    OfflineMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") OfflineMsg record, @Param("example") OfflineMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int updateByExample(@Param("record") OfflineMsg record, @Param("example") OfflineMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int updateByPrimaryKeySelective(OfflineMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_msg
     *
     * @mbggenerated Fri Oct 12 16:04:46 CST 2018
     */
    int updateByPrimaryKey(OfflineMsg record);
}