package org.blue.helper.StringHelper.persistence;

import org.apache.ibatis.annotations.Param;
import org.blue.helper.StringHelper.persistence.entity.model.QRCodeInfo;
import org.blue.helper.StringHelper.persistence.entity.model.QRCodeInfoExample;

import java.util.List;

public interface QRCodeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int countByExample(QRCodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int deleteByExample(QRCodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int insert(QRCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int insertSelective(QRCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    List<QRCodeInfo> selectByExample(QRCodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    QRCodeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") QRCodeInfo record, @Param("example") QRCodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int updateByExample(@Param("record") QRCodeInfo record, @Param("example") QRCodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int updateByPrimaryKeySelective(QRCodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRCode_info
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    int updateByPrimaryKey(QRCodeInfo record);
}