package org.blue.helper.StringHelper.persistence.entity.model;

import java.sql.Timestamp;

public class BillRecordDay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.id
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.m_id
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private Long mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.creat_time
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private Timestamp creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.update_time
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.day
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.day_count
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private Long dayCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.day_exp
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private Double dayExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.day_inc
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private Double dayInc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_record_day.status
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.id
     *
     * @return the value of bill_record_day.id
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.id
     *
     * @param id the value for bill_record_day.id
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.m_id
     *
     * @return the value of bill_record_day.m_id
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public Long getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.m_id
     *
     * @param mId the value for bill_record_day.m_id
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setmId(Long mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.creat_time
     *
     * @return the value of bill_record_day.creat_time
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public Timestamp getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.creat_time
     *
     * @param creatTime the value for bill_record_day.creat_time
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setCreatTime(Timestamp creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.update_time
     *
     * @return the value of bill_record_day.update_time
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.update_time
     *
     * @param updateTime the value for bill_record_day.update_time
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.day
     *
     * @return the value of bill_record_day.day
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.day
     *
     * @param day the value for bill_record_day.day
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.day_count
     *
     * @return the value of bill_record_day.day_count
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public Long getDayCount() {
        return dayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.day_count
     *
     * @param dayCount the value for bill_record_day.day_count
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setDayCount(Long dayCount) {
        this.dayCount = dayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.day_exp
     *
     * @return the value of bill_record_day.day_exp
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public Double getDayExp() {
        return dayExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.day_exp
     *
     * @param dayExp the value for bill_record_day.day_exp
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setDayExp(Double dayExp) {
        this.dayExp = dayExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.day_inc
     *
     * @return the value of bill_record_day.day_inc
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public Double getDayInc() {
        return dayInc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.day_inc
     *
     * @param dayInc the value for bill_record_day.day_inc
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setDayInc(Double dayInc) {
        this.dayInc = dayInc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_record_day.status
     *
     * @return the value of bill_record_day.status
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_record_day.status
     *
     * @param status the value for bill_record_day.status
     *
     * @mbggenerated Wed Nov 21 15:49:52 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}