package org.blue.helper.StringHelper.persistence.entity.model;

import java.util.Date;

public class LoginRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.id
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.user_id
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.in_time
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    private Date inTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.out_time
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    private Date outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.login_ip
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.status
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    private Integer status;

    private String memo;

    private Integer renewal;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.id
     *
     * @return the value of login_token.id
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.id
     *
     * @param id the value for login_token.id
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.user_id
     *
     * @return the value of login_token.user_id
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.user_id
     *
     * @param userId the value for login_token.user_id
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.in_time
     *
     * @return the value of login_token.in_time
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.in_time
     *
     * @param inTime the value for login_token.in_time
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.out_time
     *
     * @return the value of login_token.out_time
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.out_time
     *
     * @param outTime the value for login_token.out_time
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.token
     *
     * @return the value of login_token.token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.token
     *
     * @param token the value for login_token.token
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.login_ip
     *
     * @return the value of login_token.login_ip
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.login_ip
     *
     * @param loginIp the value for login_token.login_ip
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.status
     *
     * @return the value of login_token.status
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.status
     *
     * @param status the value for login_token.status
     *
     * @mbggenerated Tue Aug 07 16:44:21 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public Integer getRenewal() {
        return renewal;
    }

    public void setRenewal(Integer renewal) {
        this.renewal = renewal;
    }
}