package org.blue.helper.StringHelper.persistence.entity.model;

import java.util.Date;

public class QRCodeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRCode_info.id
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRCode_info.create_time
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRCode_info.modify_time
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRCode_info.image_name
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    private String imageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRCode_info.image_type
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    private String imageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRCode_info.save_path
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    private String savePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRCode_info.save_data
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    private String saveData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRCode_info.status
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRCode_info.id
     *
     * @return the value of QRCode_info.id
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRCode_info.id
     *
     * @param id the value for QRCode_info.id
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRCode_info.create_time
     *
     * @return the value of QRCode_info.create_time
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRCode_info.create_time
     *
     * @param createTime the value for QRCode_info.create_time
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRCode_info.modify_time
     *
     * @return the value of QRCode_info.modify_time
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRCode_info.modify_time
     *
     * @param modifyTime the value for QRCode_info.modify_time
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRCode_info.image_name
     *
     * @return the value of QRCode_info.image_name
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRCode_info.image_name
     *
     * @param imageName the value for QRCode_info.image_name
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRCode_info.image_type
     *
     * @return the value of QRCode_info.image_type
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRCode_info.image_type
     *
     * @param imageType the value for QRCode_info.image_type
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRCode_info.save_path
     *
     * @return the value of QRCode_info.save_path
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public String getSavePath() {
        return savePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRCode_info.save_path
     *
     * @param savePath the value for QRCode_info.save_path
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public void setSavePath(String savePath) {
        this.savePath = savePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRCode_info.save_data
     *
     * @return the value of QRCode_info.save_data
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public String getSaveData() {
        return saveData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRCode_info.save_data
     *
     * @param saveData the value for QRCode_info.save_data
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public void setSaveData(String saveData) {
        this.saveData = saveData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRCode_info.status
     *
     * @return the value of QRCode_info.status
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRCode_info.status
     *
     * @param status the value for QRCode_info.status
     *
     * @mbggenerated Mon Aug 20 10:28:28 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}